{% set name = "reacnetgenerator" %}
{% set version = "1.6.7" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tongzhugroup/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8af36afa794f9b4a2640c40a985ed98eb718250010d2e683c8390eb78ed05374

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - reacnetgenerator = reacnetgenerator.commandline:_commandline
    - reacnetgeneratorgui = reacnetgenerator.gui:gui
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - nodejs
  host:
    - python
    - pip
    - cython >=0.24.1
    - setuptools_scm
    - numpy
    - pyyaml
  run:
    - python
    - openbabel
    - rdkit >=2018.09
    - {{ pin_compatible('numpy') }}
    - pandas
    - networkx
    - matplotlib-base
    - hmmlearn >=0.2.1
    - ase
    - scour
    - tqdm
    - coloredlogs
    - lz4
    - requests
    - packaging

test:
  imports:
    - reacnetgenerator
  commands:
    - reacnetgenerator -h

about:
  home: http://github.com/tongzhugroup/reacnetgenerator
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: An automatic generator of reaction network for reactive molecular dynamics simulation.
  doc_url: https://reacnetgenerator.njzjz.win/
  dev_url: https://github.com/tongzhugroup/reacnetgenerator

extra:
  recipe-maintainers:
    - njzjz
    - DiracMD
