{% set name = "reacnetgenerator" %}
{% set version = "1.6.13" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f896e2e5f90ed0658c2cd85a7165b06d78bb6aa55aec3cd844bb37221d06dd61

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - reacnetgenerator = reacnetgenerator.commandline:_commandline
    - reacnetgeneratorgui = reacnetgenerator.gui:gui
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.26
    - make  # [unix]
    - nodejs
  host:
    - python
    - pip
    - cython >=0.24.1
    - setuptools_scm
    - scikit-build-core >=0.9.0
    - pyyaml
  run:
    - python
    - openbabel
    - rdkit >=2018.09
    - numpy
    - pandas
    - networkx
    - matplotlib-base
    - hmmlearn >=0.2.1
    - ase
    - scour
    - tqdm
    - coloredlogs
    - lz4
    - requests
    - packaging

test:
  imports:
    - reacnetgenerator
  commands:
    - reacnetgenerator -h

about:
  home: http://github.com/deepmodeling/reacnetgenerator
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: An automatic generator of reaction network for reactive molecular dynamics simulation.
  doc_url: https://docs.deepmodeling.com/projects/reacnetgenerator/
  dev_url: https://github.com/deepmodeling/reacnetgenerator

extra:
  recipe-maintainers:
    - njzjz
    - Eipgen
